// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYdcGFrtTZfbJ4W5w3uqUu06kB7RK7GE',
    appId: '1:776263851617:web:5f91f37d1da27cedb49420',
    messagingSenderId: '776263851617',
    projectId: 'ogs-chatapp',
    authDomain: 'ogs-chatapp.firebaseapp.com',
    storageBucket: 'ogs-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0maHkzYAULq8rHsAZoMCZQesV-DOijo',
    appId: '1:776263851617:android:be1fbaea00672fbcb49420',
    messagingSenderId: '776263851617',
    projectId: 'ogs-chatapp',
    storageBucket: 'ogs-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWDQvt1-IEgbmSXO6ZXUoHHzLKf2B8zY',
    appId: '1:776263851617:ios:069dfaaaa5a47f6bb49420',
    messagingSenderId: '776263851617',
    projectId: 'ogs-chatapp',
    storageBucket: 'ogs-chatapp.appspot.com',
    iosClientId: '776263851617-h2f5uad6tpek8m5kla6ise2d7jt2b1ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.ogchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWDQvt1-IEgbmSXO6ZXUoHHzLKf2B8zY',
    appId: '1:776263851617:ios:5bbb16f423f95ea7b49420',
    messagingSenderId: '776263851617',
    projectId: 'ogs-chatapp',
    storageBucket: 'ogs-chatapp.appspot.com',
    iosClientId: '776263851617-keuppq31fit8ko3s9du03r6o0gvva7on.apps.googleusercontent.com',
    iosBundleId: 'com.example.ogchat.RunnerTests',
  );
}
